language: csharp

sudo: false  # use the new container-based Travis infrastructure

install:
 - apt-get install npm

before_script:
 - chmod +x build.sh

script: 
 - npm install -g bower
 - npm install -g gulp
 - ./build.sh BuildWithTests
