language: csharp

sudo: required

install:
 - sudo apt-get install npm -qq
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 

services:
  - docker

before_script:
 - chmod +x build.sh

script:
 - ./build.sh RunTests

after_success:
 - docker build -t dzoukr/fsharping .
 - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker push dzoukr/fsharping
