language: csharp

sudo: required

mono: 3.12.0

install:
 - sudo apt-get install npm -qq

services:
  - docker

before_script:
 - chmod +x build.sh

script:
 - npm install -g bower
 - npm install -g gulp
 - ./build.sh BuildWithTests

after_success:
 - docker build -t dzoukr/fsharping .
 - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker push dzoukr/fsharping
