language: csharp

sudo: required

install:
 - sudo apt-get install npm -qq

services:
  - docker

before_script:
 - chmod +x build.sh

script:
 - npm install -g bower
 - npm install -g gulp
 - ./build.sh BuildWithTests

